
server:
  port: 8100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.web: info

eureka:
  client:
    service-url:
      default: http://localhost:8761/