server:
  port: 8500
spring:
  application:
   name: authenticationservice
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.web: debug
    
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


